.PHONY: app build up lint

app:
	python -m uv run main.py

# build:
# 	docker-compose build

# up:    build
# 	docker-compose up

lint:
	python -m uv run ruff check --select I --fix
	python -m uv run ruff format .
	python -m uv run ruff check .
